### PR TITLE
Updated podspec name.

### PR DESCRIPTION
**Pull request by ashfurrow**
I've updated the podspec name to address https://github.com/Quick/Nimble/issues/79 . After you merge this, all you'd have to do is pull, do a `git tag 0.0.2 ; tag push --tags`, then `pod trunk push`. 

Let me know if I can clarify anything!

### CODE REVIEW

**Comment by MarcoSero** [comment]
Thanks :+1:

**Comment by MarcoSero** [comment]
FYI I had to rename the podspec file name to match the new pod's name.

**Comment by ashfurrow** [comment]
Ah, good catch! I'm going to make a pull request to the [Specs](https://github.com/cocoapods/specs) repo that will point the old 0.0.1 version of Nimble to the newly named pod.

**Comment by MarcoSero** [comment]
Thanks!

**Pull request merged**
